[package]
name = "day4"
version = "0.1.0"
authors = ["Nikola Äipanov <nikola.djipanov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.1"
string-error = "0.1.0"
